# Generated by Django 5.1.4 on 2024-12-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0002_faculty_slug_group_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='description',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
