# Generated by Django 5.1.4 on 2024-12-20 10:03

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_subject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 20, 10, 3, 5, 145498, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
