# Generated by Django 5.1.4 on 2024-12-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_schedule_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
    ]
