# Generated by Django 5.1.4 on 2024-12-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0002_faculty_slug_group_slug'),
        ('timetable', '0005_remove_schedule_duration_remove_schedule_start_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('pair_number', 'group')},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='day_of_week',
        ),
    ]
